name: belajar


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: belajar.sh
        run: echo aoakak

      - name: belajar.sh
        run: |
          echo cuma buat belajar
          echo aoawkwkwkwk
